network:
  version: 2
  ethernets:
    enp87s0:
      nameservers:
        addresses: [192.168.2.2, 8.8.8.8, 8.8.4.4]
        search: [devops.lab]
  wifis:
    wlp86s0:
      nameservers:
        addresses: [192.168.2.2, 8.8.8.8, 8.8.4.4]
        search: [devops.lab]
